# Forward Pass for RNN

Let us manualy compute the forward pass for one of the RNN types. We will create a recurrent layer from RNN and perform a forward passon an input
sequence of length 3 to compute the output. We will also manually compute the forward pass and compare the result with those with RNN module from PyTorch

### Let's create the layer and assign the weights and biases for our manual computation

In [1]:
import torch
import torch.nn as nn
torch.manual_seed(1)

In [42]:
rnn_layer = nn.RNN(
    input_size=5,
    hidden_size=2,
    num_layers=1,
    batch_first=True,
)

In [43]:
w_xh = rnn_layer.weight_ih_l0
w_xh

Parameter containing:
tensor([[ 0.2188, -0.1601,  0.2718,  0.2285,  0.4317],
        [ 0.4762, -0.2395,  0.6909, -0.0817, -0.0243]], requires_grad=True)

In [44]:
w_hh = rnn_layer.weight_hh_l0
w_hh

Parameter containing:
tensor([[-0.6674, -0.4551],
        [-0.4131, -0.3024]], requires_grad=True)

In [45]:
b_xh = rnn_layer.bias_ih_l0
b_xh

Parameter containing:
tensor([ 0.5027, -0.2311], requires_grad=True)

In [46]:
b_hh = rnn_layer.bias_hh_l0
b_hh

Parameter containing:
tensor([-0.5284,  0.2721], requires_grad=True)

In [47]:
print(f"W_xh shape: {w_xh.shape}")

W_xh shape: torch.Size([2, 5])


In [48]:
print(f"W_hh shape: {w_hh.shape}")

W_hh shape: torch.Size([2, 2])


In [49]:
print(f"b_xh shape: {b_xh.shape}")

b_xh shape: torch.Size([2])


In [50]:
print(f"b_hh shape: {b_hh.shape}")

b_hh shape: torch.Size([2])


### Creating Input

In [51]:
x_seq = torch.tensor([[1.0]*5, [2.0]*5, [3.0]*5]).float()

In [52]:
x_seq

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.]])

### Reshaping th e input to (batch, seq, feature)

In [54]:
input_to_rnn = torch.reshape(x_seq, (1, 3, 5))
input_to_rnn

tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.]]])

### Computing a forward pass using the defined RNN Layer

In [55]:
output, hn = rnn_layer(input_to_rnn)

In [56]:
output

tensor([[[0.7465, 0.6976],
         [0.8144, 0.8226],
         [0.9660, 0.9580]]], grad_fn=<TransposeBackward1>)

In [57]:
hn

tensor([[[0.9660, 0.9580]]], grad_fn=<StackBackward0>)

### Manually computing the output

In [ ]:
out_man = []

for t in range(3): # 3 sequences in the input
    xt = torch.reshape(x_seq[t], (1, 5))
    print(f'Time Step {t} =>')
    print('    Input    :', xt.numpy())

    ht = torch.matmul(xt, )

In [60]:
xt = torch.reshape(x_seq[0], (1, 5))
xt

tensor([[1., 1., 1., 1., 1.]])

In [61]:
xt.numpy()

array([[1., 1., 1., 1., 1.]], dtype=float32)

In [63]:
xt.shape

torch.Size([1, 5])

In [62]:
w_xh

Parameter containing:
tensor([[ 0.2188, -0.1601,  0.2718,  0.2285,  0.4317],
        [ 0.4762, -0.2395,  0.6909, -0.0817, -0.0243]], requires_grad=True)

In [64]:
w_xh.shape

torch.Size([2, 5])

In [67]:
torch.transpose(w_xh, 0, 1)

tensor([[ 0.2188,  0.4762],
        [-0.1601, -0.2395],
        [ 0.2718,  0.6909],
        [ 0.2285, -0.0817],
        [ 0.4317, -0.0243]], grad_fn=<TransposeBackward0>)

In [69]:
ht = torch.matmul(xt, torch.transpose(w_xh, 0, 1)) + b_xh

In [70]:
prev_h = torch.zeros(ht.shape)

In [71]:
ot = ht + torch.matmul(prev_h, torch.transpose(w_hh, 0, 1)) + b_hh

In [74]:
torch.tanh(ot)

tensor([[0.7465, 0.6976]], grad_fn=<TanhBackward0>)

In [73]:
output[:, 0]

tensor([[0.7465, 0.6976]], grad_fn=<SelectBackward0>)